### ISSUE TITLE
How to configure Double Take with Project ai

### ISSUE THREAD

**Issue by thundergreen** [skrashevich/hassio-addons#15]
Hi I found your fork and was wondering how to bring those two together.. could you give me a hand?

**Comment by juanjoSanz** [comment]
Here is my Double Take code:  Port is 32168!!!

```
# detector settings (default: shown below)
detectors:
  aiserver:
    url: http://0a217ee8-ai.server:32168
    # number of seconds before the request times out and is aborted
    timeout: 15
    opencv_face_required: false
```
